### ISSUE TITLE
Add search functionality

### ISSUE THREAD

**Issue by andrewdacenko** [br-dr/best-friends#39]
Create search for users.

It should be field/page somewhere that accepts user name/surname and shows a list of possible matches - users.

**Comment by slava89** [comment]
using angular filter?

**Comment by andrewdacenko** [comment]
@slava89 Via request to server

**Comment by slava89** [comment]
using displayname from goolge is enough for starters? certain request? only request "bob marley" will return user bob marley?

**Comment by andrewdacenko** [comment]
@slava89 Yes, search for display name.

Request for 'bob' should return all users in which names there is 'bob'.
