### ISSUE TITLE
add heroku integration

### ISSUE THREAD

**Issue by andrewdacenko** [br-dr/best-friends#5]
- [x] Create/use heroku account
- [x] Add new application
- [x] Add @br-dr/core as collaborators (request for accounts)
- [x] Add integration for github

**Comment by andrewdacenko** [comment]
You can pick name for app as `bever` :smiley:

**Comment by andrewdacenko** [comment]
App is created at https://dashboard.heroku.com/apps/bever/deploy/heroku-git 

Team created.

**Comment by JackLip** [comment]
@br-dr/core 
added integration, please check is it right?

**Comment by andrewdacenko** [comment]
@JackLip all great!
