### ISSUE TITLE
Add events

### ISSUE THREAD

**Issue by andrewdacenko** [br-dr/best-friends#73]
Any user should be able to create events and invite followed people to this event. 

Event should have title, description, date and place. 

Events could be private or public. By default they should be public and can be enabled as private.

Private events can be seen only via invited people.

Public events can be seen by any authorized user.

Public events can be found via search.

Each invited user should be able to dismiss, accept or take no actions.

**Comment by slava89** [comment]
Events Page:
- new
- upcoming
- invites 
- dismissed 
- search
- archive

Add multiselect
